root@odoo-11:~# service odoo-server status
● odoo-server.service - LSB: Enterprise Business Applications
Loaded: loaded (/etc/init.d/odoo-server; bad; vendor preset: enabled)
Active: active (exited) since Sun 2017-10-22 14:01:39 UTC; 5s ago

------------------------------------------------------------
sudo apt purge python2.7         ...>to remove python

---------------------------------
apt show python2.7       to show how it ibe installed 
-----------------------------------
python --version                     to change the default python on linux
alias python="/usr/bin/python3.6"

--------------------------------------------------------------
sudo mv /usr/lib/python2.7/dist-packages/PyPDF2  /usr/lib/python3/dist-packages/


maybe the package is installed on another version on python
---------------------------------------------------------------------
locate python             --- to find all files related to software
------------------------------------------
ERROR IN ODOO RUNNIONG NOT SOLVED

Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/home/workplace/odoo/odoo/__init__.py", line 89, in <module>
    from . import modules
  File "/home/workplace/odoo/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/home/workplace/odoo/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/home/workplace/odoo/odoo/tools/__init__.py", line 8, in <module>
    from .config import config
  File "/home/workplace/odoo/odoo/tools/config.py", line 18, in <module>
    from passlib.context import CryptContext
ModuleNotFoundError: No module named 'passlib'
-----------------------------------------------------------
